// Loss computation shared by all adapters - drives FR-6.3 declaratively.
//
// The report is generated by comparing what the DIAGRAM uses against what the ADAPTER
// declares, rather than by each exporter remembering to log its own compromises. That
// matters: an exporter that forgets to report a loss is indistinguishable from a lossless
// one, and the user finds out when the round-trip fails.

import type { Attribute, Diagram, Entity, Relationship } from '../domain'

import type { CapabilitySet, Construct, LossItem } from './types'

/** Every construct a diagram actually uses, with the element that uses it. */
interface Usage {
  construct: Construct
  elementId: string
  elementKind: LossItem['elementKind']
  elementLabel: string
}

function attributeUsage(attribute: Attribute, owner: Entity): Usage[] {
  const label = `${owner.name || 'unnamed'}.${attribute.name || 'unnamed'}`
  const base: Usage = {
    construct: 'attribute',
    elementId: attribute.id,
    elementKind: 'attribute',
    elementLabel: label,
  }
  const usage: Usage[] = [base]

  const add = (construct: Construct): void => {
    usage.push({ ...base, construct })
  }

  if (attribute.dataType !== undefined) add('dataType')
  if (attribute.isPrimaryKey) add('primaryKey')
  if (attribute.isUnique) add('unique')
  if (attribute.isNullable) add('nullable')
  if (attribute.comment !== undefined) add('comment')
  if (attribute.foreignKey !== undefined) add('foreignKey')
  if (attribute.isMultivalued) add('multivaluedAttribute')
  if (attribute.isDerived) add('derivedAttribute')
  if (attribute.children !== undefined) add('compositeAttribute')

  return usage
}

function relationshipUsage(relationship: Relationship): Usage[] {
  const label = relationship.name || 'unnamed relationship'
  const base: Usage = {
    construct: 'binaryRelationship',
    elementId: relationship.id,
    elementKind: 'relationship',
    elementLabel: label,
  }
  const usage: Usage[] = []
  const add = (construct: Construct): void => {
    usage.push({ ...base, construct })
  }

  if (relationship.kind === 'nary') add('naryRelationship')
  else if (relationship.kind === 'isa') add('isaHierarchy')
  else add('binaryRelationship')

  add('cardinality')
  if (relationship.participants.some((participant) => participant.participation === 'total')) {
    add('participation')
  }
  if (relationship.isIdentifying) add('identifyingRelationship')
  if (relationship.attributes.length > 0) add('relationshipAttribute')

  const entityIds = new Set(relationship.participants.map((participant) => participant.entityId))
  if (entityIds.size < relationship.participants.length) add('recursiveRelationship')

  return usage
}

/** Everything this diagram relies on. */
export function usedConstructs(diagram: Diagram): Usage[] {
  const usage: Usage[] = []

  for (const entity of diagram.entities) {
    const label = entity.name || 'unnamed'
    usage.push({
      construct: 'entity',
      elementId: entity.id,
      elementKind: 'entity',
      elementLabel: label,
    })
    if (entity.kind === 'weak') {
      usage.push({
        construct: 'weakEntity',
        elementId: entity.id,
        elementKind: 'entity',
        elementLabel: label,
      })
    }
    if (entity.comment !== undefined) {
      usage.push({
        construct: 'comment',
        elementId: entity.id,
        elementKind: 'entity',
        elementLabel: label,
      })
    }
    if (entity.parentId !== undefined) {
      usage.push({
        construct: 'isaHierarchy',
        elementId: entity.id,
        elementKind: 'entity',
        elementLabel: label,
      })
    }
    for (const attribute of entity.attributes) usage.push(...attributeUsage(attribute, entity))
  }

  for (const relationship of diagram.relationships) usage.push(...relationshipUsage(relationship))

  if (diagram.groups.length > 0) {
    usage.push({
      construct: 'group',
      elementId: diagram.id,
      elementKind: 'diagram',
      elementLabel: diagram.name,
    })
  }
  if (Object.keys(diagram.layout.positions).length > 0) {
    usage.push({
      construct: 'position',
      elementId: diagram.id,
      elementKind: 'diagram',
      elementLabel: diagram.name,
    })
  }

  return usage
}

/** Plain-English explanations, keyed by construct and treatment. */
export type LossExplanations = Partial<Record<Construct, string>>

/**
 * Compare a diagram's usage against an adapter's declared capabilities.
 *
 * Deduplicated per element and construct, so an entity with six nullable columns
 * produces one line about nullability rather than six.
 */
export function computeLoss(
  diagram: Diagram,
  capabilities: CapabilitySet,
  explanations: LossExplanations,
): LossItem[] {
  const seen = new Set<string>()
  const report: LossItem[] = []

  for (const usage of usedConstructs(diagram)) {
    const fidelity = capabilities[usage.construct]
    if (fidelity === 'exact') continue

    const key = `${usage.construct}:${usage.elementId}`
    if (seen.has(key)) continue
    seen.add(key)

    report.push({
      elementId: usage.elementId,
      elementKind: usage.elementKind,
      elementLabel: usage.elementLabel,
      construct: usage.construct,
      treatment: fidelity,
      detail: explanations[usage.construct] ?? `Not fully representable in this format.`,
    })
  }

  return report
}
