// Public surface of the model module.

export {
  createAttribute,
  createDiagram,
  createEntity,
  createGroup,
  createParticipant,
  createRelationship,
  newAttributeId,
  newDiagramId,
  newEntityId,
  newGroupId,
  newRelationshipId,
  type CreateAttributeOptions,
  type CreateDiagramOptions,
  type CreateEntityOptions,
  type CreateGroupOptions,
  type CreateParticipantOptions,
  type CreateRelationshipOptions,
} from './factory'

export {
  attributeDepth,
  AttributeIdSchema,
  AttributeSchema,
  CardinalitySchema,
  DiagramIdSchema,
  DiagramMetaSchema,
  DiagramSchema,
  EntityIdSchema,
  EntityKindSchema,
  EntitySchema,
  ForeignKeyRefSchema,
  FORMAT_VERSION,
  GroupIdSchema,
  GroupSchema,
  LayoutStateSchema,
  MAX_COMPOSITE_DEPTH,
  NotationSchema,
  ParticipantSchema,
  ParticipationSchema,
  PointSchema,
  RelationshipIdSchema,
  RelationshipKindSchema,
  RelationshipSchema,
  SpecializationSchema,
  ViewportSchema,
} from './schema'

export type {
  Attribute,
  AttributeId,
  AttributeInput,
  Cardinality,
  Diagram,
  DiagramId,
  DiagramInput,
  DiagramMeta,
  Entity,
  EntityId,
  EntityInput,
  EntityKind,
  ForeignKeyRef,
  Group,
  GroupId,
  LayoutState,
  Notation,
  Participant,
  Participation,
  Point,
  Relationship,
  RelationshipId,
  RelationshipInput,
  RelationshipKind,
  Specialization,
  Viewport,
} from './types'
